### ISSUE TITLE
Change consumer to support broker failure + other improvements

### ISSUE THREAD

**Issue by kwiknik** [FuseByExample/external-mq-fabric-client#3]
We've customised this project quite a bit. We now combine it with Ruby and Cucumber, these communicate with Fabric to simulate broker failure by starting and stopping containers containing brokers in the same group. Our customised version of this artifact is downloaded within the Cucumber demo feature and parameterised with CLI system properties specifying the message count, message delay and whether a producer or consumer should be spawned.

There are a few improvements we'd like to suggest to this reference example, listed here as comments on our own modified version:
1. Up to the point of `session` creation the code for both producer and consumer is common. This code is pushed into a common parent class.
2. Many identical properties are defined in the pom for the different profiles you've defined. Those common ones (such as `broker.username`, `broker.password`, `zookeeper.url`) can be pushed into the `<properties>` section to avoid this duplication.
3. Your `SimpleConsumer` breaks the message consumption loop if the message is `null`. This isn't supportive of simulating broker failure, since occasionally a `null` is received when the broker fails before the client receives an `EOFException`. In our version we continue until an expected number of messages is consumed.

Regarding (3) - we realise our modification is flawed in that the consumer will run indefinitely if the producer hasn't sent the expected number of messages.

We'd like to know how best to modify the consumer to support a `null` message from broker failure _and_ recognise when the broker's running but there are no more messages to consume.

Must you define advisory messages to be certain of this latter situation?

Could you please update your example to correctly support both broker failure and termination upon no more messages? We'd love to learn of the correct approach to handle both scenarios.

**Comment by scranton** [comment]
Re item 1: We intentionally wanted the code to be pure JMS and straightforward (versus optimized and highly engineered) so that its (hopefully) very clear to the user what is happening. Real applications would have a lot more going on in their producer and consumer code, so wouldn't necessarily be able to reuse a common base class... Plus I'd normally recommend using Apache Camel (camel.apache.org) for client code anyways :-)

Re item 2: already done in last push I did 3 days ago ;-)

Re item 3: Good point about the null. "Last message" is different for all applications. I can modify the example to have a special "Last Message" command message that the consumer waits for before shutting down. I can also put some code in to log connection lost and restore event so you can see / know when you have live access to a broker. Note: sometimes the ActiveMQ client libraries will transparently break and restore connections to load balance across a network of brokers, so losing a connection does not always mean broker failed - just means the client lost a connection.

Thanks for the feedback!!!

**Comment by scranton** [comment]
BTW - I was thinking of merging this example back into the Getting Started with ActiveMQ project (https://github.com/FuseByExample/getting_started_with_activemq) that this one was originally derived from. What do you think of that?

**Comment by kwiknik** [comment]
1. I can understand you wanting entirely distinct producer and consumer definitions for clarity.
2. Good call with the property sharing!
3. Ah of course, we can just check for special last message content.. Great, well we can easily make that change ourselves. Thanks for the suggestion.

I think the connection loss/restore is already logged, no? We were monitoring the failure scenarios and each point of simulated broker failure showed some connection loss message then printed a series of new brokers it said were "added" then showed one of those was connected to the new master.

Looking at the ActiveMQ project you link to, personally I wouldn't merge back. It was very pleasing for us to find this simple project which was tailored for Fabric specifically; all too often we've hit brick walls where neither the Fuse MQ nor Fuse ESB docs provide an answer. They do deal with a lot of Fabric configuration but miss certain key elements. Several times we weren't able to find answers in the Fabric documentation hub [here](http://fuse.fusesource.org/fabric/docs/index.html) since some of its information is out of date. Without answers received in the forums we wouldn't have been able to make any progress with Fabric.

One example of missed information is that a JAR must have a `BundleActivator` defined, along with the necessary manifest headers, if it's an application you want to turn into a FAB. It doesn't mention this in the [FAB docs](http://fuse.fusesource.org/bundle/overview.html) once; rather they eagerly emphasise that you have to do almost nothing to turn a JAR into an OSGI-ified FAB. We presumed your internals were converting a `public static void main` into a `BundleActivator#start` and only recently from the forums were we enlightened.  It isn't even mentioned in the [FAB educational video](http://www.youtube.com/watch?v=Pwi30_0Vu-Q). We found it ironic that, as with the docs, the video highlights that without FAB you need to use Maven Bundle plugin and such to OSGI-ify your JAR, yet in reality to convert a JAR application into a FAB it turns out you'd likely want this anyway to automate generation of the manifest header for `BundleActivator`!

The other project is pure Fuse MQ right now isn't it? I imagine the pom will become cluttered if you merge, since you'll have non-fabric MQ dependencies for the non-fabric Maven profiles and Fabric MQ dependencies for the Fabric profiles. Since you've expressed a desire for clarity, I think the complexity of combined Fabric/FuseMQ readme and pom sections would be undesirable.

Personally I think such drawbacks outweigh the benefit of having only one project to maintain and update. It's your call though.
